# Generated by Django 4.1 on 2023-12-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='기타', max_length=100),
        ),
    ]
