# Generated by Django 4.1 on 2023-12-03 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
