# Generated by Django 4.1 on 2023-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_carddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
