# Generated by Django 4.1 on 2023-12-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_carddata_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='category',
            field=models.CharField(default='기타', max_length=100),
        ),
        migrations.AddField(
            model_name='carddata',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
