# Generated by Django 4.1 on 2023-12-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_carddata_category_carddata_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddata',
            name='post',
        ),
    ]
